import React from "react";

export const UNITS = [
  {
    id: "1",
    name: "DPS",
    class: "DPS",
    stars: 3,
    skillset: {
      s1: {
        name: "Quick Shot",
        type: "Basic",
        chases: null,
        causes: "Bleeding",
        cooldown: 1,
        description: "Shoots a quick shot at an enemy",
      },
      s2: {
        name: "Air Strike",
        type: "Active",
        chases: null,
        causes: "Knockup",
        cooldown: 3,
        description: "Knocks enemies up in the air",
      },
      s3: {
        name: "Sky Hunter",
        type: "Passive",
        chases: "Knockup",
        causes: "Knockup",
        cooldown: 1,
        description:
          "Striker's attacks will knock up enemies that are already in the air",
      },
    },
  },
  {
    id: "2",
    name: "TANK",
    class: "TANK",
    stars: 3,
    skillset: {
      s1: {
        name: "Shield Bash",
        type: "Basic",
        chases: null,
        causes: "Knockback",
        cooldown: 1,
        description: "Bashes enemies with a shield, knocking them back",
      },
      s2: {
        name: "Ground Slam",
        type: "Active",
        chases: null,
        causes: "Falling",
        cooldown: 2,
        description: "Knocks enemies down to the ground",
      },
      s3: {
        name: "Airborne Smash",
        type: "Passive",
        chases: "Knockup",
        causes: "Repel",
        cooldown: 1,
        description: "Launches enemies into the air",
      },
    },
  },
  {
    id: "3",
    name: "HEALER",
    class: "Support",
    stars: 3,
    skillset: {
      s1: {
        name: "Kick",
        type: "Basic",
        chases: null,
        causes: null,
        cooldown: 1,
        description: "Kicks an enemy",
      },
      s2: {
        name: "Healing Wind",
        type: "Active",
        chases: null,
        causes: "Heal",
        cooldown: 2,
        description: "Heals allies in the area",
      },
      s3: {
        name: "Seal of Protection",
        type: "Passive",
        chases: "Repel",
        causes: "Seal",
        cooldown: 0,
        description: "Seals the skill of enemies that are repelled",
      },
    },
  },
  {
    id: "4",
    name: "SHADOW BLADE",
    class: "Assassin",
    stars: 4,
    skillset: {
      s1: {
        name: "Shadow Strike",
        type: "Basic",
        chases: null,
        causes: "Blind",
        cooldown: 1,
        description: "Strikes from the shadows, reducing enemy accuracy.",
      },
      s2: {
        name: "Blood Siphon",
        type: "Active",
        chases: null,
        causes: "Bleeding",
        cooldown: 3,
        description: "A deep cut that causes the enemy to bleed profusely.",
      },
      s3: {
        name: "Executioner",
        type: "Passive",
        chases: "Bleeding",
        causes: "Knockback",
        cooldown: 1,
        description:
          "When an enemy is bleeding, delivers a kick that knocks them back.",
      },
    },
  },
  {
    id: "5",
    name: "PYROMANCER",
    class: "Mage",
    stars: 4,
    skillset: {
      s1: {
        name: "Fireball",
        type: "Basic",
        chases: null,
        causes: "Burn",
        cooldown: 1,
        description: "Hurls a ball of fire at a single target.",
      },
      s2: {
        name: "Inferno Column",
        type: "Active",
        chases: null,
        causes: "Knockup",
        cooldown: 4,
        description: "Creates a pillar of flame that launches enemies upward.",
      },
      s3: {
        name: "Ignite Spirit",
        type: "Passive",
        chases: "Seal",
        causes: "Burn",
        cooldown: 1,
        description:
          "If an enemy is Sealed, they immediately burst into flames.",
      },
    },
  },
  {
    id: "6",
    name: "GUARDIAN",
    class: "Paladin",
    stars: 5,
    skillset: {
      s1: {
        name: "Holy Bolt",
        type: "Basic",
        chases: null,
        causes: null,
        cooldown: 1,
        description: "A bolt of light that strikes the enemy.",
      },
      s2: {
        name: "Justice Hammer",
        type: "Active",
        chases: null,
        causes: "Repel",
        cooldown: 3,
        description: "Swings a massive hammer to repel all nearby foes.",
      },
      s3: {
        name: "Consecration",
        type: "Passive",
        chases: "Falling",
        causes: "Seal",
        cooldown: 1,
        description: "When an enemy falls, pins them down with a holy seal.",
      },
    },
  },
];
